configuracao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('controle/', include('controle.urls'))
]

controle/urls.py
from django.urls import path
from .views import *

app_name = 'controle'

urlpatterns = [
    path('entradas', entradas, name='entradas'),
    path('saidas', saidas, name='saidas'),
    path('alterarcaixa/<int:id>', alterar_caixa, name='alterarcaixa'),
    path('excluir_caixa/<int:id>', excluir_caixa, name='excluir_caixa'),
    path('totalanual', totalanual, name='totalanual'),
    path('login', login, name='login')
]

controle/models.py
from django.db import models


class Categoria(models.Model):
    descricao = models.CharField(max_length=32)

    def __str__(self):
        return self.descricao


class Caixa(models.Model):
    data = models.DateField()
    descricao = models.CharField(max_length=32)
    quantidade_de_x_dividido = models.FloatField()
    nome_devedor = models.CharField(max_length=12, null=True, blank=True)
    valor_mensal = models.FloatField()
    valor_total = models.FloatField()
    tipo = models.CharField(max_length=8, choices=[("entradas", "Entradas"), ("saidas", "Saídas")])
    situacao = models.CharField(max_length=8, choices=[("fixo", "Fixo"), ("variavel", "Variável")])
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)

    def __str__(self):
        return self.descricao

controle/views.py
from django.shortcuts import render
from .models import *
from .utilitarios.card import *
from django.shortcuts import redirect
from django.db.models import Sum


def login(requisicao):
    return render(requisicao, 'telaDeLogin.html')


def entradas(requisicao):
    todos_entradas = Caixa.objects.filter(tipo='entradas')
    if requisicao.method == 'POST':
        entrada = Caixa()
        entrada.data = requisicao.POST.get('data_entrada', None)
        entrada.descricao = requisicao.POST.get('descricao_entrada', None)
        entrada.quantidade_de_x_dividido = requisicao.POST.get('quantidade_de_x_dividido', None)
        entrada.valor_mensal = requisicao.POST.get('valor_mensal', None)
        entrada.valor_total = requisicao.POST.get('valor_total', None)
        entrada.tipo = 'entradas'
        entrada.situacao = requisicao.POST.get('situacao')
        if Categoria.objects.filter(descricao__iexact=requisicao.POST.get('categoriaentrada')).exists():
            entrada.categoria = Categoria.objects.get(descricao=requisicao.POST.get('categoriaentrada', None))
        else:
            categoria = Categoria(descricao=requisicao.POST.get('categoriaentrada'))
            categoria.save()
            entrada.categoria = categoria
        entrada.save()
    valor_divida_mensal = 0
    for saida in Caixa.objects.filter(tipo='saidas'):
        valor_divida_mensal = valor_divida_mensal + saida.valor_mensal
    valor_entrada_mensal = 0
    for entrada in todos_entradas:
        valor_entrada_mensal = valor_entrada_mensal + entrada.valor_mensal
    falta = valor_divida_mensal - valor_entrada_mensal
    if falta < 0:
        falta = 0
    cards = [
        Card(1, 'DIVIDA MENSAL', valor_divida_mensal, 'danger'),
        Card(1, 'ENTRADA MENSAL', valor_entrada_mensal, 'danger'),
        Card(1, 'FALTA', falta, 'danger'),
        Card(1, 'VALOR DA DIVIDA DO PROXIMO MÊS', 550, 'danger'),
    ]
    contexto = {
        'entradas': todos_entradas,
        'categoriaentrada': Categoria.objects.all(),
        'cards': cards,
    }
    return render(requisicao, 'entradas.html', contexto)


def alterar_caixa(requisicao, id=None):
    if requisicao.method == 'POST':
        caixa = Caixa.objects.get(id=id)
        caixa.data = requisicao.POST.get('data_alterar', None)
        caixa.descricao = requisicao.POST.get('descricao_alterar', None)
        caixa.quantidade_de_x_dividido = requisicao.POST.get('quantidade_de_x_dividido_alterar', None)
        caixa.valor_mensal = requisicao.POST.get('valor_mensal_alterar', None)
        caixa.valor_total = requisicao.POST.get('valor_total_alterar', None)
        caixa.situacao = requisicao.POST.get('situacao_alterar')

        if Categoria.objects.filter(descricao__iexact=requisicao.POST.get('categoria_alterar')).exists():
            caixa.categoria = Categoria.objects.get(descricao=requisicao.POST.get('categoria_alterar', None))
        else:
            categoria = Categoria(descricao=requisicao.POST.get('categoria_alterar'))
            categoria.save()
            caixa.categoria = categoria
        caixa.save()

    return redirect('controle:' + caixa.tipo)


def excluir_caixa(requisicao, id=None):
    if requisicao.method == 'POST':
        caixa = Caixa.objects.get(id=id)
        tipo = caixa.tipo
        caixa.delete()
        return redirect('controle:' + tipo)
    return render()


def saidas(requisicao, ):
    todos_saidas = Caixa.objects.filter(tipo='saidas')
    if requisicao.method == 'POST':
        saida = Caixa()
        saida.data = requisicao.POST.get('data_saida', None)
        saida.descricao = requisicao.POST.get('descricao_saida', None)
        saida.quantidade_de_x_dividido = requisicao.POST.get('quantidade_de_x_dividido', None)
        saida.valor_mensal = requisicao.POST.get('valor_mensal', None)
        saida.valor_total = requisicao.POST.get('valor_total', None)
        saida.tipo = 'saidas'
        saida.situacao = requisicao.POST.get('situacao')
        if Categoria.objects.filter(descricao__iexact=requisicao.POST.get('categoriasaida')).exists():
            saida.categoria = Categoria.objects.get(descricao=requisicao.POST.get('categoriasaida', None))
        else:
            categoria = Categoria(descricao=requisicao.POST.get('categoriasaida'))
            categoria.save()
            saida.categoria = categoria
        saida.save()

    contexto = {
        'saidas': todos_saidas,
        'categoriasaida': Categoria.objects.all(),

    }
    return render(requisicao, "saidas.html", contexto)


def totalanual(request):
    totalentradas = []
    for x in range(1, 13):
        valores = Caixa.objects.filter(tipo='entradas', data__month=x).aggregate(Sum('valor_mensal')).get('valor_mensal__sum')
        if valores is not None:
            totalentradas.append(valores)
        else:
            totalentradas.append(0)
    totalsaidas = []
    for x in range(1, 13):
        valores = Caixa.objects.filter(tipo='saidas', data__month=x).aggregate(Sum('valor_mensal')).get('valor_mensal__sum')
        if valores is not None:
            totalsaidas.append(valores)
        else:
            totalsaidas.append(0)
    contexto = {
        'totalentradas': totalentradas,
        'totalsaidas': totalsaidas
    }
    return render(request, "totalanual.html", contexto)

controle/templates/menu.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Controle Finaçeiro</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/sb-admin-2.min.css' %}">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="telainicial.html">
            <div class="sidebar-brand-icon rotate-n-0">
                <i class="fas fa-file-invoice-dollar"></i></div>
            <div class="sidebar-brand-text mx-3">CONTROLE FINACEIRO</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <div class="sidebar-heading">
            Entradas e Saídas
        </div>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'controle:entradas' %}">
                <i class="fas fa-coins"></i> <span>Entradas</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'controle:saidas' %}">
                <i class="fas fa-coins"></i> <span>Saídas</span></a>
        </li>


        <!-- Divider -->
        <hr class="sidebar-divider">


        <div class="sidebar-heading">
            Total Anual
        </div>


        <!-- Nav Item - Tables -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'controle:totalanual' %}">
                <i class="fas fa-money-check-alt"></i> <span>Total Anual</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">


        <!-- Sidebar Message -->


    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->


                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->

                    <!-- Nav Item - Alerts -->


                    <!-- Nav Item - Messages -->


                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Pâmela Araujo</span>
                            <i class="fas fa-user"></i>
                        </a>
                        <!-- Dropdown - User Information -->

                    </li>
                    <div class="topbar-divider d-none d-sm-block"></div>
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="{% url 'controle:login' %}" id="userDropdown1" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Sair</span>
                            <i class="fas fa-sign-out-alt"></i> </a>
                        <!-- Dropdown - User Information -->

                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->
            <div class="row">


                {%block menu%}
                {%endblock%}
            </div>
        </div>

        <!-- /.col-lg-3 -->


    </div>

</body>
</html>

controle/templates/telaDeLogin.html
{% load static %}

<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }








</style>
<!-- Custom styles for this template -->
<link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
<!--<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

</head>
<body class="text-center">

<form class="form-signin" action="" method="post">
    {% csrf_token %}

    <img class="mb-4" src="{% static 'USUARIO.png' %}" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Ensira seu login</h1>
    <label for="email_logar" class="sr-only">Email</label>
    <input type="email" name="email_logar" id="email_logar" class="form-control"
           placeholder="Email"
           required
           autofocus>
    <label for="senha_logar" class="sr-only">Senha</label>
    <input  type="password" name="senha_logar" id="senha_logar" class="form-control"
           placeholder="Senha">
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Lembrar de mim
        </label>
    </div>


    <div class="g-recaptcha"
         data-sitekey="6LcePAATAAAAAGPRWgx90814DTjgt5sXnNbV5WaW"></div>
    <script src='https://www.google.com/recaptcha/api.js'></script>


    <button class="col-md-12 btn btn-lg btn-primary" type="submit">Logar</button>

    <p>

    </p>

    <button class="col-md-12 btn btn-lg btn-primary" data-toggle="modal" data-target="#exampleModal">Cria novo Usuário
    </button>
    <p class="mt-5 mb-3 text-muted">PXFASHION</p>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>

</form>
<!-- Modal -->

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cadastro</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="col" align="left">
                        <label>Nome: </label>
                    </div>
                    <input type="text" name="nome_cadastro" id="nome_cadastro" class="form-control"
                           placeholder="Nome"
                           required
                           autofocus>
                    <div class="col" align="left">
                        <label>Email: </label>
                    </div>
                    <input type="email" name="email_cadastro" id="email_cadastro" class="form-control"
                           placeholder="Email"
                           required
                           autofocus>
                    <div class="col" align="left">
                        <label>Senha: </label>
                    </div>
                    <input type="password" name="senha_cadastro" id="senha_cadastro" class="form-control"
                           placeholder="Senha"
                    >
                    <div class="col" align="left">
                        <label>Confirme a senha: </label>
                    </div>
                    <input type="password" name="confirmasenha" id="confirmasenha" class="form-control"
                           placeholder="Confirme a senha"
                           required>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

controle/templates/totalanual.html
{% extends "menu.html" %}
{%block menu%}
{% load static %}
<!-- entradas -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Entradas</h6>
    </div>
    <div class="card-body">
        <div class="chart-bar">
            <canvas id="entradas"></canvas>
        </div>
        <hr>
        Grafico de entradas por mês.
    </div>
</div>

</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>


<script type="text/javascript">
    // Set new default font family and font color to mimic Bootstrap's default styling
Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
Chart.defaults.global.defaultFontColor = '#858796';

function number_format(number, decimals, dec_point, thousands_sep) {
  // *     example: number_format(1234.56, 2, ',', ' ');
  // *     return: '1 234,56'
  number = (number + '').replace(',', '').replace(' ', '');
  var n = !isFinite(+number) ? 0 : +number,
    prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
    sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
    dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
    s = '',
    toFixedFix = function(n, prec) {
      var k = Math.pow(10, prec);
      return '' + Math.round(n * k) / k;
    };
  // Fix for IE parseFloat(0.55).toFixed(0) = 0;
  s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
  if (s[0].length > 3) {
    s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
  }
  if ((s[1] || '').length < prec) {
    s[1] = s[1] || '';
    s[1] += new Array(prec - s[1].length + 1).join('0');
  }
  return s.join(dec);
}

// Bar Chart Example
var ctx = document.getElementById("entradas");
var myBarChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outobro", "Novembro", "Dezembro"],
    datasets: [{
      label: "Revenue",
      backgroundColor: "#4e73df",
      hoverBackgroundColor: "#2e59d9",
      borderColor: "#4e73df",
      data: [
        {% for valor in totalentradas %}
            {{valor}},
        {% endfor %}
      ],
    }],
  },
  options: {
    maintainAspectRatio: false,
    layout: {
      padding: {
        left: 10,
        right: 25,
        top: 25,
        bottom: 0
      }
    },
    scales: {
      xAxes: [{
        time: {
          unit: 'month'
        },
        gridLines: {
          display: false,
          drawBorder: false
        },
        ticks: {
          maxTicksLimit: 12
        },
        maxBarThickness: 25,
      }],
      yAxes: [{
        ticks: {
          min: 0,
          maxTicksLimit: 5,
          padding: 10,
          // Include a dollar sign in the ticks
          callback: function(value, index, values) {
            return '$' + number_format(value);
          }
        },
        gridLines: {
          color: "rgb(234, 236, 244)",
          zeroLineColor: "rgb(234, 236, 244)",
          drawBorder: false,
          borderDash: [2],
          zeroLineBorderDash: [2]
        }
      }],
    },
    legend: {
      display: false
    },
    tooltips: {
      titleMarginBottom: 10,
      titleFontColor: '#6e707e',
      titleFontSize: 14,
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      borderColor: '#dddfeb',
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      caretPadding: 10,
      callbacks: {
        label: function(tooltipItem, chart) {
          var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
          return datasetLabel + ': $' + number_format(tooltipItem.yLabel);
        }
      }
    },
  }
});


</script>


<!-- saidas -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Saídas</h6>
    </div>
    <div class="card-body">
        <div class="chart-bar">
            <canvas id="saidas"></canvas>
        </div>
        <hr>
        Grafico de saídas por mês.
    </div>
</div>

</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>


<script type="text/javascript">
    // Set new default font family and font color to mimic Bootstrap's default styling
Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
Chart.defaults.global.defaultFontColor = '#858796';

function number_format(number, decimals, dec_point, thousands_sep) {
  // *     example: number_format(1234.56, 2, ',', ' ');
  // *     return: '1 234,56'
  number = (number + '').replace(',', '').replace(' ', '');
  var n = !isFinite(+number) ? 0 : +number,
    prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
    sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
    dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
    s = '',
    toFixedFix = function(n, prec) {
      var k = Math.pow(10, prec);
      return '' + Math.round(n * k) / k;
    };
  // Fix for IE parseFloat(0.55).toFixed(0) = 0;
  s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
  if (s[0].length > 3) {
    s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
  }
  if ((s[1] || '').length < prec) {
    s[1] = s[1] || '';
    s[1] += new Array(prec - s[1].length + 1).join('0');
  }
  return s.join(dec);
}

// Bar Chart Example
var ctx = document.getElementById("saidas");
var myBarChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outobro", "Novembro", "Dezembro"],
    datasets: [{
      label: "Revenue",
      backgroundColor: "#4e73df",
      hoverBackgroundColor: "#2e59d9",
      borderColor: "#4e73df",
      data: [
        {% for valor in totalsaidas %}
            {{valor}},
        {% endfor %}
      ],
    }],
  },
  options: {
    maintainAspectRatio: false,
    layout: {
      padding: {
        left: 10,
        right: 25,
        top: 25,
        bottom: 0
      }
    },
    scales: {
      xAxes: [{
        time: {
          unit: 'month'
        },
        gridLines: {
          display: false,
          drawBorder: false
        },
        ticks: {
          maxTicksLimit: 12
        },
        maxBarThickness: 25,
      }],
      yAxes: [{
        ticks: {
          min: 0,
          maxTicksLimit: 5,
          padding: 10,
          // Include a dollar sign in the ticks
          callback: function(value, index, values) {
            return '$' + number_format(value);
          }
        },
        gridLines: {
          color: "rgb(234, 236, 244)",
          zeroLineColor: "rgb(234, 236, 244)",
          drawBorder: false,
          borderDash: [2],
          zeroLineBorderDash: [2]
        }
      }],
    },
    legend: {
      display: false
    },
    tooltips: {
      titleMarginBottom: 10,
      titleFontColor: '#6e707e',
      titleFontSize: 14,
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      borderColor: '#dddfeb',
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      caretPadding: 10,
      callbacks: {
        label: function(tooltipItem, chart) {
          var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
          return datasetLabel + ': $' + number_format(tooltipItem.yLabel);
        }
      }
    },
  }
});


</script>


{% endblock %}